const USER = 'USER'
const DATA_FETCHED = 'DATA_FETCHED'
const DATA_FAILED = 'DATA_FAILED'
const FILTER = 'FILTER'
const ADD_VERB = 'ADD_VERB'

export { USER, DATA_FETCHED, DATA_FAILED, FILTER, ADD_VERB }
